services:
  cat:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  dog:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  nginx:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M

  prometheus:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  grafana:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  node-exporter:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M

  cadvisor:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  portainer:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
