upstream pets {
    server cat:3000;
    server dog:3000;
}

server {
    listen 80;

    location / {
        proxy_pass http://pets;
    }

    location /cat {
        proxy_pass http://cat:3000/;
    }

    location /dog {
        proxy_pass http://dog:3000/;
    }
}
